// {
//     pic: File {
//       _events: [Object: null prototype] {},
//       _eventsCount: 0,
//       _maxListeners: undefined,
//       size: 92173,
//       path: 'C:\\Users\\Saaketh\\AppData\\Local\\Temp\\upload_6352ece15eba641ff2283b43a3831d70',
//       name: 'unnamed.jpg',
//       type: 'image/jpeg',
//       hash: null,
//       lastModifiedDate: 2020-09-09T05:33:57.381Z,
//       _writeStream: WriteStream {
//         _writableState: [WritableState],
//         writable: false,
//         _events: [Object: null prototype] {},
//         _eventsCount: 0,
//         _maxListeners: undefined,
//         path: 'C:\\Users\\Saaketh\\AppData\\Local\\Temp\\upload_6352ece15eba641ff2283b43a3831d70',
//         fd: null,
//         flags: 'w',
//         mode: 438,
//         start: undefined,
//         autoClose: true,
//         pos: undefined,
//         bytesWritten: 92173,
//         closed: false,
//         [Symbol(kFs)]: [Object],
//         [Symbol(kCapture)]: false,
//         [Symbol(kIsPerformingIO)]: false
//       },
//       [Symbol(kCapture)]: false
//     },
//     sign: File {
//       _events: [Object: null prototype] {},
//       _eventsCount: 0,
//       _maxListeners: undefined,
//       size: 334849,
//       path: 'C:\\Users\\Saaketh\\AppData\\Local\\Temp\\upload_6038b3bbc1e9c932e11f1f54a86390ed',
//       name: '2426_diwali-name-wallpaper-115.jpg',
//       type: 'image/jpeg',
//       hash: null,
//       lastModifiedDate: 2020-09-09T05:33:57.383Z,
//       _writeStream: WriteStream {
//         _writableState: [WritableState],
//         writable: false,
//         _events: [Object: null prototype] {},
//         _eventsCount: 0,
//         _maxListeners: undefined,
//         path: 'C:\\Users\\Saaketh\\AppData\\Local\\Temp\\upload_6038b3bbc1e9c932e11f1f54a86390ed',
//         fd: null,
//         flags: 'w',
//         mode: 438,
//         start: undefined,
//         autoClose: true,
//         pos: undefined,
//         bytesWritten: 334849,
//         closed: false,
//         [Symbol(kFs)]: [Object],
//         [Symbol(kCapture)]: false,
//         [Symbol(kIsPerformingIO)]: false
//       },
//       [Symbol(kCapture)]: false
//     }
//   }
